version: '3.7'

services:
  backend:
    build:
      context: ./simpleapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
    - my-network
    depends_on:
       database :
         condition: service_healthy

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - ./Database/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usr -d db" ]
      interval: 10s
      retries: 5
      timeout: 5s

  httpd:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
